#!/bin/bash

export OMP_NUM_THREADS=28
NumThread=16
BatchSize=64
ImageSize=128
Degree=0
ScaleFactor="(1,1)"
aRange="(1,1)"
bRange="(0,0)"
ColorFlag=True
if [ "$ColorFlag" == "True" ]; then
    Color=Color
else
    Color=Gray
fi
ModelName=${ImageSize}_${Color}_Blob_SVM_Model
GMMFile=${ImageSize}_${Color}_Blob_GMM.dat
PCAFile=${ImageSize}_${Color}_Blob_PCA.dat
KMEANSFile=${ImageSize}_${Color}_Blob_KMEANS.dat
ParamsFile=${ImageSize}_${Color}_Blob_Params
NumPrincipal=128
NumGaussian=32
PatchSize=16
Stride=1
NumBin=8
GaussianScale=1
Radius=64
NumGrid=1


time ./shiftablePinwheelBlobPyramidKMeansModel  -i ../Leaf/Train_128_0_${Color}.dat -c 1 -t ${NumThread} -b ${BatchSize} -m ${ModelName} --GMMFile ${GMMFile} --PCAFile ${PCAFile} --threshold 0.01 --numGMMExample 128 --numPrincipal ${NumPrincipal} --numGaussian ${NumGaussian} --imageSize ${ImageSize} --paramsFileName ${ParamsFile} --patchSize ${PatchSize} --stride 8 --numBin ${NumBin} --gaussianScale ${GaussianScale} --KMeansFile ${KMEANSFile} --NumGrid ${NumGrid} --Radius ${Radius}  +RTS -N${NumThread}  -RTS  --logpolarFlag

time ./trainShiftablePinwheelBlobPyramid  -i ../Leaf/Train_128_0_${Color}.dat -c 1 -t ${NumThread} -b ${BatchSize} -m ${ModelName} --GMMFile ${GMMFile} --PCAFile ${PCAFile} --threshold -15 --numGMMExample 375 --numPrincipal ${NumPrincipal} --numGaussian ${NumGaussian} --imageSize ${ImageSize} --paramsFileName ${ParamsFile} --patchSize ${PatchSize} --stride ${Stride} --numBin ${NumBin} --gaussianScale ${GaussianScale} --KMeansFile ${KMEANSFile} --NumGrid ${NumGrid} --Radius ${Radius}  +RTS -N${NumThread}  -RTS --logpolarFlag

time ./predictShiftablePinwheelBlobPyramid  -i ../Leaf/Test_128_0_${Color}.dat -c 1 -t ${NumThread} -b ${BatchSize} -m ${ModelName} --GMMFile ${GMMFile} --PCAFile ${PCAFile} --threshold -15 --numGMMExample 60 --numPrincipal ${NumPrincipal} --numGaussian ${NumGaussian} --imageSize ${ImageSize} --paramsFileName ${ParamsFile} --patchSize ${PatchSize} --stride ${Stride} --numBin ${NumBin} --gaussianScale ${GaussianScale} --KMeansFile ${KMEANSFile} --NumGrid ${NumGrid} --Radius ${Radius}  +RTS -N${NumThread}  -RTS --logpolarFlag

time ./predictShiftablePinwheelBlobPyramid  -i "../Leaf/Test_Color_(128,128)_0_(0.5,1)_(1,1)_(0,0)_1.dat" -c 1 -t ${NumThread} -b ${BatchSize} -m ${ModelName} --GMMFile ${GMMFile} --PCAFile ${PCAFile} --threshold -15 --numGMMExample 60 --numPrincipal ${NumPrincipal} --numGaussian ${NumGaussian} --imageSize ${ImageSize} --paramsFileName ${ParamsFile} --patchSize ${PatchSize} --stride ${Stride} --numBin ${NumBin} --gaussianScale ${GaussianScale} --KMeansFile ${KMEANSFile} --NumGrid ${NumGrid} --Radius ${Radius}  +RTS -N${NumThread}  -RTS --logpolarFlag

# time ./predictShiftablePinwheelBlobPyramid  -i ../Leaf/Test_128_45_${Color}.dat -c 1 -t ${NumThread} -b ${BatchSize} -m ${ModelName} --GMMFile ${GMMFile} --PCAFile ${PCAFile} --threshold -15 --numGMMExample 60 --numPrincipal ${NumPrincipal} --numGaussian ${NumGaussian} --imageSize ${ImageSize} --paramsFileName ${ParamsFile} --patchSize ${PatchSize} --stride ${Stride} --numBin ${NumBin} --gaussianScale ${GaussianScale} --KMeansFile ${KMEANSFile} --NumGrid ${NumGrid} --Radius ${Radius}  +RTS -N${NumThread}  -RTS --logpolarFlag
