#!/bin/bash

ghc -i../.. -j4 -O2 Main.hs -o main

ghc -i../.. -j4 -O2 -threaded -rtsopts PlotFilteredImage.hs -o plot

ghc -i../.. -j4 -O2 -threaded -rtsopts PlotFilterResponse.hs -o plotFilterResponse
ghc -i../.. -j4 -O2 -threaded -rtsopts PlotFilterResponseSIFT.hs -o plotFilterResponseSIFT

