#!/bin/bash

cabal exec -- ghc -i../.. -lgomp -lstdc++ -lblas  -lprotobuf -lopencv_imgcodecs -lcaffe -lhdf5 -lhdf5_hl $OBJPATH/linear.o $OBJPATH/tron.o $SVMPATH/svm.o -O2 ConvertLabeledArray.hs -o convertLabeledArray


