#!/bin/bash
FLAGS="-j4 --make -O2 -threaded -rtsopts -fno-liberate-case -funfolding-use-threshold1000 -funfolding-keeness-factor1000 -fllvm -optlo-O3 -funbox-strict-fields -XBangPatterns"
LIBS="-lstdc++ -lopencv_video -lopencv_core -lopencv_imgcodecs -lopencv_highgui"
cabal exec -- ghc $FLAGS  $LIBS -i../.. Opencv/opticalflow.o Main.hs -o main
